apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-api-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-api-deployment
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
