apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  labels:
    app: python-api-deployment
spec:
  selector:
    app: python-api
  ports:
    - name: http     
      port: 8000
      targetPort: 8000
