apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-api-monitor
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: python-api-deployment
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
