apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-api-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-api
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
